

service: embarca-challenge

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  deploymentBucket:
    name: embarca-challenge
  stage: dev



functions:
  lambda-1:
    name: embarca-challenge-lambda-1
    handler: handler.hello_1
  lambda-2:
    name: embarca-challenge-lambda-2
    handler: handler.hello_2
