service: embarca-challenge

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  deploymentBucket:
    name: embarca-challenge
  stage: dev


functions:
  lambda-1:
    name: embarca-challenge-lambda-1
    handler: handler.hello_1
  lambda-2:
    name: embarca-challenge-lambda-2
    handler: handler.hello_2



stepFunctions:
  stateMachines:
    embarca-challenge:
      name: embarca-challenge-step-function
      definition:
        Comment: A description of my state machine
        StartAt: lambda_handler_1
        States:
          lambda_handler_1:
            Type: Task
            Resource:
              Fn::GetAtt: ["lambda-1", "Arn"]
            ResultSelector:
              responseBody.$: "$.body"
            ResultPath: "$.lambda_handler_1_result"
            Next: lambda_handler_2
          lambda_handler_2:
            Type: Task
            Resource:
              Fn::GetAtt: ["lambda-2", "Arn"]
            ResultSelector:
              responseBody.$: "$.body"
            ResultPath: "$.lambda_handler_2_result"
            End: true


plugins:
  - serverless-step-functions
  - serverless-dotenv-plugin
